### ISSUE TITLE
forge-pull keyboard shortcuts not working

### ISSUE THREAD

**Issue by beeuhtricks** [magit/forge#115]
As far as I can tell all of the other Forge shortcuts in the `transient` buffers are working but when I hit `F` in magit I get only the core magit commands, and hitting `y` or `Y` gives me `Unbound suffix: 'y' (Use 'C-g' to abort, '?' for help)`. This happens even after I've run `forge-pull` from `M-x`. Not sure what I'm doing wrong.

**Comment by tarsius** [comment]
See #109.

**Comment by tarsius** [comment]
> You closed [this] but I’m pretty sure it’s different from [#109]. I do use `:after magit` in my config, and I have the Forge suffixes in branch and fetch and so forth, they’re just missing in pull.

Ah, didn't read careful enough.

That's because I didn't add those commands to that transient. You can add them yourself though.

**Comment by tarsius** [comment]
Hm, actually I did add them there too... let me check.

**Comment by tarsius** [comment]
Have you customized the bindings in that transient. Maybe the `transient-append-suffix` in `forge.el` cannot add something after `m` binding because there isn't an `m` binding at that time anymore?

**Comment by beeuhtricks** [comment]
> Ah I see, the binding is added after `m`, which is inside a group that is only available when `magit-pull-or-fetch` is non-nil.

Oh, that makes sense. So I should just set `magit-pull-or-fetch` to `t`?

**Comment by tarsius** [comment]
If you would like the other bindings too. Otherwise you would have to add after `e` yourself. You can copy the forms from `forge.el` and adjust them accordingly.

**Comment by beeuhtricks** [comment]
It might be a good idea to add that to the documentation, as it was not specified and it suggests that `F y` should work out of the box.

**Comment by glasser** [comment]
Agreed — I found this confusing. Alternatively, the docs could just suggest `f y` instead as the standard way to get started (which is mentioned in a few places)?

**Comment by tarsius** [comment]
I've updated the documentation.

**Comment by jefftrull** [comment]
Unfortunately the documentation still suggests 'F y', for example [here](https://magit.vc/manual/forge/Initial-Pull.html#Initial-Pull). This threw me as well and it's only by finding this issue that I was able to make forward progress.

**Comment by tarsius** [comment]
I have fixed that "example" now. Are there others you are aware of?

**Comment by jefftrull** [comment]
The blog post in which you introduced forge: https://emacsair.me/2018/12/19/forge-0.1/

**Comment by tarsius** [comment]
Fixed it there too. Thanks!

**Comment by artpelling** [comment]
I just setup forge according to the documentary and I encountered the same confusion. https://github.com/magit/forge/issues/115#issuecomment-488783506 still does not clarify this.

**Comment by artpelling** [comment]
As a matter of fact, even with `magit-pull-or-fetch` set to `t`, I cannot access the commands with the suggested `f y` or `F y`.
It works via `N f f`.

I am using
Magit 20210123.446, Git 2.17.1, Emacs 27.1, gnu/linux

**Comment by tarsius** [comment]
The key bindings changed a bit, see https://emacsair.me/2021/10/14/forge-0.3/.

The bindings now are:

- <kbd>f n</kbd> forge-pull
- <kbd>f N</kbd> forge-pull-notifications
- <kbd>F n</kbd> forge-pull, only available if magit-pull-or-fetch is non-nil, but I intend to improve that
- <kbd>F N</kbd> forge-pull-notifications, only available if magit-pull-or-fetch is non-nil, but I intend to improve that
- <kbd>N f f</kbd> forge-pull
- <kbd>N f n</kbd> forge-pull-notifications

If you use something like `evil-collections` then things get shuffled around.

**Comment by artpelling** [comment]
Thanks, I the new keybindings showed up on the transient. I was following the instructions on magit.vc and it had the old ones there when I commented. Now, it shows the new keybindings. Thanks, everything works! :)
