### ISSUE TITLE
error in process sentinel: forge--list-topics-1: Symbol’s function definition is void: partial

### ISSUE THREAD

**Issue by jeremymeng** [magit/forge#757]
upgrade packages to latest version and now getting an error after fetching topics

> Pulling Azure/azure-sdk-for-js...done
Storing Azure/azure-sdk-for-js...done
Git finished
error in process sentinel: forge--list-topics-1: Symbol’s function definition is void: partial
error in process sentinel: Symbol’s function definition is void: partial

##  magit-version

> Magit 20250204.1930 [>= 20250204.1930], Transient 20250201.1314, Forge 20250205.1920, Git 2.48.1, Emacs 31.0.50, gnu/linux

**Comment by tarsius** [comment]
1. Is `llama` installed and is its version `0.6.0`?
2. Have you tried restarting Emacs yet? If not, do that now and then try to reproduce.
3. If you an still reproduce, uninstall `forge`. Exit Emacs. Restart Emacs. Reinstall `forge`. Now it should work.

**Comment by jeremymeng** [comment]
I didn't install `llama` directly.  It's probably installed as a prerequisite of `forge`:

```
drwxr-xr-x   2 meng users  4096 Feb  5 16:28 llama-20250201.1300  
```

> 3\. If you an still reproduce, uninstall `forge`. Exit Emacs. Restart Emacs. Reinstall `forge`. Now it should work.

Tried removing `forge` and `llama`, restarting emacs, and reinstalling `forge`.  Still the same error

**Comment by jeremymeng** [comment]
Is this related? I saw it in the repo, but no similar thing in distributed package

https://github.com/magit/forge/blob/add7868aaf7b8538f086d3a007c412419d08ead9/.dir-locals.el#L3-L5

**Comment by tarsius** [comment]
Yes.

What do you mean by "no similar thing in distributed package"? Maybe "I could not find another package that does that". (Asking because after all Forge itself is a "distributed package".)

Have you set `enable-local-variables` to `nil`? If so, and you want to stick to that, try...

... well, I was going to suggest that you add `read-symbol-shorthands` to `permanently-enabled-local-variables`, but turns out that's already a member of the default value of this variable.

**Comment by tarsius** [comment]
Oh! Now I understand what you mean by "distributed package". It's... quite obvious. On it!

**Comment by tarsius** [comment]
I had already tried to include that file in the package, but despite being the maintainer of `package-build.el` had forgotten that entries of `:defaults`'s `:exclude` can no longer be overridden.

Fixed in https://github.com/melpa/melpa/commit/37e21947bfaa74a6e941e886b302a87fb45b3fb3.

**Comment by artenator** [comment]
I am having this issue when running `forge-list-notifications`

```
mapcar: Symbol’s function definition is void: partial
```

```
Magit v4.3.0, Transient 0.8.4, Forge 0.4.7, Git 2.39.5, Emacs 29.4, darwin
```

I tried reinstalling my packages but it did not resolve the issue

**Comment by tarsius** [comment]
> I tried reinstalling my packages but it did not resolve the issue

Is the `llama` package installed? What version of that package is installed? What package manager are you using?

**Comment by artenator** [comment]
> Is the llama package installed? What version of that package is installed? 
I did not install it myself, but I'm guessing it was installed on its own from the dependencies of other packages. Running `describe-function` on `llama` takes me to `llama.el`, where the version is `;; Package-Version: 0.6.0`

> What package manager are you using?
I'm using Doom Emacs, which uses `straight.el` I believe.

> Did you restart Emacs after reinstalling your packages?
Yes 👍 

---

I see that it seems that `partial` is aliased in the `.dir-locals.el` file in the `forge` package, but I'm unsure as to why it's not taking effect.

**Comment by tarsius** [comment]
I cannot reproduce this with Straight. I tried both Emacs 31.0.50 and 29.4.

Check whether both `straight/repos/forge/.dir-locals.el` and `straight/repos/forge/.dir-locals.el` exist.

**Comment by artenator** [comment]
Thanks @tarsius !

I noticed it still didn't work for me when calling `forge-list-notifications`. Adding the same `read-symbol-shorthands` local vars (from the commit you referenced) to `forge-notify.el` fixed it for me. Let me know if you'd be open to a contribution of this and I will open a PR, but understandable if you'd prefer me not to make such a small/simple contribution. 

Appreciate all your work!

**Comment by tarsius** [comment]
Ah, I forgot that I had started `partial` in more libraries. Pushed a commit to set the shorthands in more files.
